# -*- coding: utf-8 -*-
# Copyright (C) 2010 CENATIC: Centro Nacional de Referencia de
# Aplicacion de las TIC basadas en Fuentes Abiertas, Spain.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#   Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in
#   the documentation and/or other materials provided with the
#   distribution.
#
#   Neither the name of the CENATIC nor the names of its contributors
#   may be used to endorse or promote products derived from this
#   software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# You may contact the copyright holder at: Fundacion CENATIC, Edificio
# de Servicios Sociales: C/ Vistahermosa, 1, 3ra planta, 06200
# Almendralejo (Badajoz), Spain

from CTK.consts import *

BACK_LINK = LINK_HREF % ('javascript:history.go(-1)','⇇')

LANG = [ # ISO 639-1
('es','Español'),
('en','Inglés'),
('aa','Afar'),
('ab','Abjaso'),
('ae','Avéstico'),
('af','Afrikaans'),
('ak','Akano'),
('am','Amárico'),
('an','Aragonés'),
('ar','Árabe'),
('as','Asamés'),
('av','Avar'),
('ay','Aimara'),
('az','Azerí'),
('ba','Baskir'),
('be','Bielorruso'),
('bg','Búlgaro'),
('bh','Bhojpurí'),
('bi','Bislama'),
('bm','Bambara'),
('bn','Bengalí'),
('bo','Tibetano'),
('br','Bretón'),
('bs','Bosnio'),
('ca','Catalán'),
('ce','Checheno'),
('ch','Chamorro'),
('co','Corso'),
('cr','Cree'),
('cs','Checo'),
('cu','Eslavo'),
('cv','Chuvasio'),
('cy','Galés'),
('da','Danés'),
('de','Alemán'),
('dv','Maldivo'),
('dz','Dzongkha'),
('ee','Ewe'),
('el','Griego'),
('en','Inglés'),
('eo','Esperanto'),
('es','Español'),
('et','Estonio'),
('eu','Euskera'),
('fa','Persa'),
('ff','Fula'),
('fi','Finés'),
('fj','Fiyiano'),
('fo','Feroés'),
('fr','Francés'),
('fy','Frisón'),
('ga','Irlandés'),
('gd','Gaélico'),
('gl','Gallego'),
('gn','Guaraní'),
('gu','Guyaratí'),
('gv','Manés'),
('ha','Hausa'),
('he','Hebreo'),
('hi','Hindi'),
('ho','Hiri'),
('hr','Croata'),
('ht','Haitiano'),
('hu','Húngaro'),
('hy','Armenio'),
('hz','Herero'),
('ia','Interlingua'),
('id','Indonesio'),
('ie','Occidental'),
('ig','Igbo'),
('ii','Yi'),
('ik','Inupiaq'),
('io','Ido'),
('is','Islandés'),
('it','Italiano'),
('iu','Inuktitut'),
('ja','Japonés'),
('jv','Javanés'),
('ka','Georgiano'),
('kg','Kongo'),
('ki','Kikuyu'),
('kj','Kuanyama'),
('kk','Kazajo'),
('kl','Groenlandés'),
('km','Camboyano'),
('kn','Canarés'),
('ko','Coreano'),
('kr','Kanuri'),
('ks','Cachemiro'),
('ku','Kurdo'),
('kv','Komi'),
('kw','Córnico'),
('ky','Kirguís'),
('la','Latín'),
('lb','Luxemburgués'),
('lg','Luganda'),
('li','Limburgués'),
('ln','Lingala'),
('lo','Lao'),
('lt','Lituano'),
('lu','Luba-katanga'),
('lv','Letón'),
('mg','Malgache'),
('mh','Marshalés'),
('mi','Maorí'),
('mk','Macedonio'),
('ml','Malayalam'),
('mn','Mongol'),
('mo','Moldavo'),
('mr','Maratí'),
('ms','Malayo'),
('mt','Maltés'),
('my','Birmano'),
('na','Nauruano'),
('nb','Noruego'),
('nd','Ndebele'),
('ne','Nepalí'),
('ng','Ndonga'),
('nl','Neerlandés'),
('nn','Nynorsk'),
('no','Noruego'),
('nr','Ndebele'),
('nv','Navajo'),
('ny','Chichewa'),
('oc','Occitano'),
('oj','Ojibwa'),
('om','Oromo'),
('or','Oriya'),
('os','Osético'),
('pa','Panyabí'),
('pi','Pali'),
('pl','Polaco'),
('ps','Pastú'),
('pt','Portugués'),
('qu','Quechua'),
('rm','Retorrománico'),
('rn','Kirundi'),
('ro','Rumano'),
('ru','Ruso'),
('rw','Ruandés'),
('sa','Sánscrito'),
('sc','Sardo'),
('sd','Sindhi'),
('se','Sami'),
('sg','Sango'),
('si','Cingalés'),
('sk','Eslovaco'),
('sl','Esloveno'),
('sm','Samoano'),
('sn','Shona'),
('so','Somalí'),
('sq','Albanés'),
('sr','Serbio'),
('ss','Suazi'),
('st','Sesotho'),
('su','Sundanés'),
('sv','Sueco'),
('sw','Suajili'),
('ta','Tamil'),
('te','Telugú'),
('tg','Tayiko'),
('th','Tailandés'),
('ti','Tigriña'),
('tk','Turcomano'),
('tl','Tagalo'),
('tn','Setsuana'),
('to','Tongano'),
('tr','Turco'),
('ts','Tsonga'),
('tt','Tártaro'),
('tw','Twi'),
('ty','Tahitiano'),
('ug','Uigur'),
('uk','Ucraniano'),
('ur','Urdu'),
('uz','Uzbeko'),
('ve','Venda'),
('vi','Vietnamita'),
('wl','Walisiano'),
('vo','Volapük'),
('wa','Valón'),
('wo','Wolof'),
('xh','Xhosa'),
('yi','Yídish'),
('yo','Yoruba'),
('za','Chuan'),
('zh','Chino'),
('zu','Zulú'),
]

LEN_TITL = 256
LEN_SUBJ = 45
LEN_DESC = 8192
