PACKAGES =  \
basics      \
curl        \
ffmpeg      \
imagemagick \
cherokee

install:
	python ./install.py --fast $(PACKAGES)

clean:
	rm -f *.pyc *~ packages/*~ packages/*.pyc


.PHONY: install clean
