# DAM platform installer
#
# Author:    Alvaro Lopez Ortega, <alvaro@octality.com>
# Copyright: CENATIC, 2008
# License:   MIT

download:
	cd images && python download.py
	cd video  && python download.py

.PHONY: download
